### PR TITLE
Fix for 1.1.69

### LINKED ISSUE #1112: 1.1.69 - Something went wrong
## ℹ Computer information

- Spotify version: 1.1.69.612.gb7409abc
- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)

1. spicetify apply
2. black screen
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_
Spicetify applies correctly
### ❌ Actual result

_What is the actual result of the above steps?_
Spicetify shows a blank screen
## 📷 Screenshots

_Are there any useful screenshots?_
Screen Shot 2021-09-29 at 9 06 57 AM

### PR DESCRIPTION
**Pull request by itsmeow**
Fixes #1112

This one's a doozy

# Changes
- **BREAKING:** Removes `Spicetify.PlaybackControl`
- **BREAKING:** Removes hook `Spicetify.Player.origin2`
- Adds `Spicetify.Player.playUri(uri, context, options)` (replacement for `Spicetify.PlaybackControl.playUri`)
- Fixes Lyrics Plus queue callback
- Fixes New Releases/Reddit Card play button
- Fixes `bookmark.js` play seeking
- Improves popupLyrics error messaging
- Fixes `shuffle+.js` play injection
- Fixes `Spicetify.Queue`
- Updates `Spicetify.test()` to reflect actual contents of Spicetify object
- Adds additional checks to `Spicetify.test()` for new contents
- Fixes `Spicetify.addToQueue` and `Spicetify.removeFromQueue`
- Fixes hook `Spicetify._sidebarItemToClone`
- Fixes hook `Spicetify._cloneSidebarItem`
- Fixes hook `Spicetify.Platform`
- Adds hook to disable a call to `document.exitPictureInPicture()` from the client itself, resulting in `popupLyrics.js` randomly exiting.

### CODE REVIEW

File: Extensions/keyboardShortcut.js [hunk 1]
```diff
@@ -383,14 +383,17 @@ function VimBind() {
             findButton.click();
             return;
         }
-
+        alert("Let me know where you found this button, please. I can't click this for you without that information.");
```
Comment (afonsojramos) [inline Extensions/keyboardShortcut.js:386]: We need to not forget about this.

**Review by afonsojramos — APPROVED** [review]
